/*
 * Testbench: TEMPLATE_IP
 *
 * Description: Functional verification testbench
 * Author:      Generated by Vitis HLS Automation Environment
 */

#include <iostream>
#include <cstdlib>
#include "../src/TEMPLATE_IP.hpp"

// ============================================================
// Test Utilities
// ============================================================
static int error_count = 0;
static int test_count  = 0;

template<typename T>
void check(const char* test_name, T actual, T expected) {
    test_count++;
    if (actual != expected) {
        std::cerr << "[FAIL] " << test_name
                  << " — expected: " << expected
                  << ", got: " << actual << std::endl;
        error_count++;
    } else {
        std::cout << "[PASS] " << test_name << std::endl;
    }
}

void check_bool(const char* test_name, bool condition) {
    test_count++;
    if (!condition) {
        std::cerr << "[FAIL] " << test_name << std::endl;
        error_count++;
    } else {
        std::cout << "[PASS] " << test_name << std::endl;
    }
}

// ============================================================
// Test Cases
// ============================================================

void test_basic() {
    std::cout << "--- Basic Functionality ---" << std::endl;
    // TODO: Add basic test cases
}

void test_boundary() {
    std::cout << "--- Boundary Conditions ---" << std::endl;
    // TODO: Add min/max/zero/edge-case tests
}

void test_sequence() {
    std::cout << "--- Sequential Behavior ---" << std::endl;
    // TODO: Add sequence-of-operations tests (if IP has state)
}

// ============================================================
// Main
// ============================================================
int main() {
    std::cout << "==========================================" << std::endl;
    std::cout << "  Testbench: TEMPLATE_IP" << std::endl;
    std::cout << "==========================================" << std::endl;

    test_basic();
    test_boundary();
    // test_sequence();  // Enable if the IP has internal state

    std::cout << "==========================================" << std::endl;
    std::cout << "  Results: " << (test_count - error_count) << "/" << test_count << " passed" << std::endl;
    if (error_count == 0) {
        std::cout << "  *** ALL TESTS PASSED ***" << std::endl;
    } else {
        std::cout << "  *** " << error_count << " TEST(S) FAILED ***" << std::endl;
    }
    std::cout << "==========================================" << std::endl;

    return error_count;
}
