/*
 * TEMPLATE_IP — HLS IP Implementation
 *
 * Description: <brief description>
 * Author:      Generated by Vitis HLS Automation Environment
 */

#include "TEMPLATE_IP.hpp"

// ============================================================
// Helper Functions
// ============================================================

// ============================================================
// Top-Level Function
// ============================================================
void TEMPLATE_IP(/* parameters */) {
    // ---- Interface Pragmas ----
    // #pragma HLS INTERFACE s_axilite port=return
    // #pragma HLS INTERFACE axis      port=in_stream
    // #pragma HLS INTERFACE axis      port=out_stream

    // ---- Implementation ----

}
