/*
 * TEMPLATE_IP — HLS IP Header
 *
 * Description: <brief description>
 * Author:      Generated by Vitis HLS Automation Environment
 */

#ifndef TEMPLATE_IP_HPP
#define TEMPLATE_IP_HPP

// ============================================================
// Vitis HLS Includes
// ============================================================
#include <ap_int.h>
// #include <ap_fixed.h>       // Uncomment for fixed-point types
// #include <hls_stream.h>     // Uncomment for streaming interfaces
// #include <ap_axi_sdata.h>   // Uncomment for AXI-Stream side channels

// ============================================================
// Constants
// ============================================================
// const int BUFFER_SIZE = 256;

// ============================================================
// Type Definitions
// ============================================================
// typedef ap_uint<8>       data_t;
// typedef ap_fixed<16, 1>  coeff_t;
// typedef ap_fixed<32, 16> acc_t;

// ============================================================
// Top Function Prototype
// ============================================================
void TEMPLATE_IP(/* parameters */);

#endif // TEMPLATE_IP_HPP
