/*
 * Testbench: depthwise_conv
 *
 * Description: Comprehensive functional verification testbench covering
 *              identity kernel, uniform kernel, negative values with ReLU,
 *              saturation/clamping, large-frame stress test, and small-frame
 *              border/padding verification.
 * Author:      Generated by Vitis HLS Automation Environment
 */

#include <iostream>
#include <cstdlib>
#include <cmath>
#include <cstring>
#include "../src/depthwise_conv.hpp"

// ============================================================
// Test Utilities
// ============================================================
static int error_count = 0;
static int test_count  = 0;

void check_pixel(const char* test_name, int row, int col,
                 int actual, int expected) {
    test_count++;
    if (actual != expected) {
        std::cerr << "[FAIL] " << test_name
                  << " pixel(" << row << "," << col << ")"
                  << " -- expected: " << expected
                  << ", got: " << actual << std::endl;
        error_count++;
    }
}

// ============================================================
// Golden Reference Model (double-precision C++)
// ============================================================
// Computes the depthwise convolution for one channel using plain C++.
// Input/output are flat arrays in row-major order.
void golden_depthwise_conv(
    const int8_t* input,    // H x W input
    int8_t* output,         // H x W output
    const int8_t weights[9],
    int32_t bias,
    int height,
    int width,
    int shift,
    bool relu
) {
    for (int r = 0; r < height; r++) {
        for (int c = 0; c < width; c++) {
            int32_t acc = bias;
            for (int ky = 0; ky < 3; ky++) {
                for (int kx = 0; kx < 3; kx++) {
                    int img_r = r + ky - 1;
                    int img_c = c + kx - 1;
                    int8_t pixel = 0;
                    if (img_r >= 0 && img_r < height &&
                        img_c >= 0 && img_c < width) {
                        pixel = input[img_r * width + img_c];
                    }
                    acc += (int32_t)pixel * (int32_t)weights[ky * 3 + kx];
                }
            }
            // ReLU
            if (relu && acc < 0) acc = 0;
            // Requantize
            int32_t shifted = acc >> shift;
            // Clamp
            if (shifted > 127) shifted = 127;
            if (shifted < -128) shifted = -128;
            output[r * width + c] = (int8_t)shifted;
        }
    }
}

// ============================================================
// Helper: Run one test case through the DUT and compare
// ============================================================
void run_test(
    const char* test_name,
    const int8_t* input,
    const int8_t weights_arr[9],
    int32_t bias_val,
    int height,
    int width,
    int shift,
    bool relu,
    const int8_t* expected_output  // If NULL, use golden model
) {
    std::cout << "--- " << test_name << " (" << height << "x" << width << ") ---" << std::endl;

    // Compute golden reference if not provided
    int num_pixels = height * width;
    int8_t* golden = new int8_t[num_pixels];
    if (expected_output != NULL) {
        std::memcpy(golden, expected_output, num_pixels);
    } else {
        golden_depthwise_conv(input, golden, weights_arr, bias_val,
                              height, width, shift, relu);
    }

    // Set up HLS streams
    hls::stream<axis8_t> data_in("data_in");
    hls::stream<axis8_t> data_out("data_out");

    // Fill input stream
    for (int i = 0; i < num_pixels; i++) {
        axis8_t pkt;
        pkt.data = input[i];
        pkt.keep = 1;
        pkt.strb = 1;
        pkt.last = (i == num_pixels - 1) ? 1 : 0;
        data_in.write(pkt);
    }

    // Prepare weight array for DUT
    weight_t w[9];
    for (int i = 0; i < 9; i++) w[i] = weights_arr[i];

    // Call DUT
    depthwise_conv(
        data_in, data_out,
        w,
        (bias_t)bias_val,
        (dim_t)height, (dim_t)width,
        (shift_t)shift,
        (ap_uint<1>)(relu ? 1 : 0)
    );

    // Read and compare output
    int test_errors = 0;
    bool tlast_seen = false;
    int tlast_index = -1;

    for (int i = 0; i < num_pixels; i++) {
        if (data_out.empty()) {
            std::cerr << "[FAIL] " << test_name
                      << " -- output stream empty at pixel " << i << std::endl;
            error_count++;
            test_errors++;
            break;
        }
        axis8_t pkt = data_out.read();
        int8_t actual = (int8_t)(ap_int<8>)pkt.data;
        int row = i / width;
        int col = i % width;

        check_pixel(test_name, row, col, (int)actual, (int)golden[i]);
        if (actual != golden[i]) test_errors++;

        // Track TLAST
        if (pkt.last == 1) {
            tlast_seen = true;
            tlast_index = i;
        }
    }

    // Verify TLAST was on the last pixel
    test_count++;
    if (!tlast_seen) {
        std::cerr << "[FAIL] " << test_name << " -- TLAST never asserted" << std::endl;
        error_count++;
    } else if (tlast_index != num_pixels - 1) {
        std::cerr << "[FAIL] " << test_name << " -- TLAST at index " << tlast_index
                  << ", expected " << num_pixels - 1 << std::endl;
        error_count++;
    }

    // Verify no extra output
    test_count++;
    if (!data_out.empty()) {
        std::cerr << "[FAIL] " << test_name << " -- extra data in output stream" << std::endl;
        error_count++;
    }

    if (test_errors == 0) {
        std::cout << "[PASS] " << test_name << " -- all " << num_pixels
                  << " pixels match" << std::endl;
    } else {
        std::cout << "[INFO] " << test_name << " -- " << test_errors
                  << " pixel errors" << std::endl;
    }

    delete[] golden;
}

// ============================================================
// Test 1: Identity Kernel (Basic Correctness)
// ============================================================
void test_identity_kernel() {
    const int H = 8, W = 8;
    int8_t input[H * W];
    for (int r = 0; r < H; r++)
        for (int c = 0; c < W; c++)
            input[r * W + c] = (int8_t)(r * W + c);  // 0..63

    int8_t weights[9] = {0, 0, 0, 0, 1, 0, 0, 0, 0};
    run_test("Test1_IdentityKernel", input, weights, 0, H, W, 0, false, NULL);
}

// ============================================================
// Test 2: Uniform Kernel (Accumulation + Border Behavior)
// ============================================================
void test_uniform_kernel() {
    const int H = 6, W = 6;
    int8_t input[H * W];
    for (int i = 0; i < H * W; i++) input[i] = 1;

    int8_t weights[9] = {1, 1, 1, 1, 1, 1, 1, 1, 1};

    // Expected output: corners=4, edges=6, interior=9
    int8_t expected[H * W] = {
        4, 6, 6, 6, 6, 4,
        6, 9, 9, 9, 9, 6,
        6, 9, 9, 9, 9, 6,
        6, 9, 9, 9, 9, 6,
        6, 9, 9, 9, 9, 6,
        4, 6, 6, 6, 6, 4
    };

    run_test("Test2_UniformKernel", input, weights, 0, H, W, 0, false, expected);
}

// ============================================================
// Test 3: Negative Values + ReLU
// ============================================================
void test_negative_relu() {
    const int H = 8, W = 8;
    int8_t input[H * W];
    // Checkerboard: +10 / -10
    for (int r = 0; r < H; r++)
        for (int c = 0; c < W; c++)
            input[r * W + c] = ((r + c) % 2 == 0) ? 10 : -10;

    int8_t weights[9] = {1, 1, 1, 1, 1, 1, 1, 1, 1};

    // Use golden model with relu_en=1
    run_test("Test3_NegativeReLU", input, weights, 0, H, W, 0, true, NULL);
}

// ============================================================
// Test 4: Saturation / Clamping Test
// ============================================================
void test_saturation() {
    const int H = 8, W = 8;

    // Part A: Positive saturation
    {
        int8_t input[H * W];
        for (int i = 0; i < H * W; i++) input[i] = 127;

        int8_t weights[9] = {127, 127, 127, 127, 127, 127, 127, 127, 127};

        // Interior MAC = 9 * 127 * 127 = 145,161. >> 7 = 1134. Clamped to 127.
        run_test("Test4a_PositiveSaturation", input, weights, 0, H, W, 7, false, NULL);
    }

    // Part B: Negative saturation
    {
        int8_t input[H * W];
        for (int i = 0; i < H * W; i++) input[i] = -128;

        int8_t weights[9] = {127, 127, 127, 127, 127, 127, 127, 127, 127};

        // Interior MAC = 9 * (-128) * 127 = -146,304. >> 7 = -1143. Clamped to -128.
        run_test("Test4b_NegativeSaturation", input, weights, 0, H, W, 7, false, NULL);
    }
}

// ============================================================
// Test 5: Stress Test (64x64 Gradient Pattern)
// ============================================================
void test_stress_64x64() {
    const int H = 64, W = 64;
    int8_t input[H * W];

    // Gradient pattern: pixel[r][c] = ((r+c) % 256) - 128
    for (int r = 0; r < H; r++)
        for (int c = 0; c < W; c++)
            input[r * W + c] = (int8_t)(((r + c) % 256) - 128);

    // Sobel-like vertical edge detector
    int8_t weights[9] = {1, 2, 1, 0, 0, 0, -1, -2, -1};

    run_test("Test5_Stress64x64", input, weights, 0, H, W, 2, false, NULL);
}

// ============================================================
// Test 6: Small Frame Border/Padding Verification (4x4)
// ============================================================
void test_small_frame_4x4() {
    const int H = 4, W = 4;
    int8_t input[H * W];
    for (int i = 0; i < H * W; i++) input[i] = 1;

    int8_t weights[9] = {1, 1, 1, 1, 1, 1, 1, 1, 1};

    // Expected: exact per-pixel values from the spec
    int8_t expected[H * W] = {
        4, 6, 6, 4,
        6, 9, 9, 6,
        6, 9, 9, 6,
        4, 6, 6, 4
    };

    run_test("Test6_SmallFrame4x4", input, weights, 0, H, W, 0, false, expected);
}

// ============================================================
// Test 7: Bias and Shift Combined
// ============================================================
void test_bias_and_shift() {
    const int H = 4, W = 4;
    int8_t input[H * W];
    for (int i = 0; i < H * W; i++) input[i] = 10;

    int8_t weights[9] = {0, 0, 0, 0, 1, 0, 0, 0, 0}; // identity
    int32_t bias_val = 100; // Add 100 to each accumulator
    // Output = (10 + 100) >> 2 = 110 >> 2 = 27

    run_test("Test7_BiasAndShift", input, weights, bias_val, H, W, 2, false, NULL);
}

// ============================================================
// Main
// ============================================================
int main() {
    std::cout << "==========================================" << std::endl;
    std::cout << "  Testbench: depthwise_conv" << std::endl;
    std::cout << "==========================================" << std::endl;

    test_identity_kernel();
    test_uniform_kernel();
    test_negative_relu();
    test_saturation();
    test_stress_64x64();
    test_small_frame_4x4();
    test_bias_and_shift();

    std::cout << "==========================================" << std::endl;
    std::cout << "  Results: " << (test_count - error_count) << "/" << test_count << " passed" << std::endl;
    if (error_count == 0) {
        std::cout << "  *** ALL TESTS PASSED ***" << std::endl;
    } else {
        std::cout << "  *** " << error_count << " TEST(S) FAILED ***" << std::endl;
    }
    std::cout << "==========================================" << std::endl;

    return error_count;
}
