#!/usr/bin/env tclsh
# ============================================================
# Full Build Script (C-Sim → Synthesis → Co-Sim → Export)
# Generated by Vitis HLS Automation Environment
# ============================================================

# --- Configuration (modify per IP) ---
set IP_NAME    "TEMPLATE_IP"
set TOP_FUNC   "TEMPLATE_IP"
set FPGA_PART  "xc7z020clg400-1"
set CLK_PERIOD 10

# --- Flow Control (set to 1 to enable) ---
set RUN_CSIM   1
set RUN_CSYNTH 1
set RUN_COSIM  0
set RUN_EXPORT 0

# --- Project Setup ---
open_project proj_${IP_NAME}
set_top ${TOP_FUNC}

# Source files
add_files     src/${IP_NAME}.cpp
add_files     src/${IP_NAME}.hpp

# Testbench files
add_files -tb tb/tb_${IP_NAME}.cpp

# --- Solution ---
open_solution "sol1" -flow_target vivado
set_part ${FPGA_PART}
create_clock -period ${CLK_PERIOD} -name default

# --- Execute Flows ---
if {${RUN_CSIM}} {
    puts "=============================="
    puts "  Running C-Simulation"
    puts "=============================="
    csim_design -clean
}

if {${RUN_CSYNTH}} {
    puts "=============================="
    puts "  Running C-Synthesis"
    puts "=============================="
    csynth_design
}

if {${RUN_COSIM}} {
    puts "=============================="
    puts "  Running Co-Simulation"
    puts "=============================="
    cosim_design -trace_level all
}

if {${RUN_EXPORT}} {
    puts "=============================="
    puts "  Exporting Design"
    puts "=============================="
    export_design -format ip_catalog -description "${IP_NAME} HLS IP" -vendor "user" -version "1.0"
}

close_project
puts "=============================="
puts "  Build Complete: ${IP_NAME}"
puts "=============================="
exit
