#!/usr/bin/env tclsh
# ============================================================
# C-Simulation Script
# Generated by Vitis HLS Automation Environment
# ============================================================

# --- Configuration (modify per IP) ---
set IP_NAME    "TEMPLATE_IP"
set TOP_FUNC   "TEMPLATE_IP"
set FPGA_PART  "xc7z020clg400-1"
set CLK_PERIOD 10

# --- Project Setup ---
open_project proj_${IP_NAME}
set_top ${TOP_FUNC}

# Source files
add_files     src/${IP_NAME}.cpp
add_files     src/${IP_NAME}.hpp

# Testbench files
add_files -tb tb/tb_${IP_NAME}.cpp

# --- Solution ---
open_solution "sol1" -flow_target vivado
set_part ${FPGA_PART}
create_clock -period ${CLK_PERIOD} -name default

# --- Run C-Simulation ---
csim_design -clean

close_project
exit
