/*
 * depthwise_conv -- HLS IP Implementation
 *
 * Description: 3x3 depthwise convolution with INT8 data path,
 *              line buffer architecture, same-padding, optional ReLU,
 *              and shift-based requantization. Processes one channel
 *              per invocation at II=1 (one pixel per clock cycle).
 * Author:      Generated by Vitis HLS Automation Environment
 */

#include "depthwise_conv.hpp"

// ============================================================
// Top-Level Function
// ============================================================
void depthwise_conv(
    hls::stream<axis8_t>& data_in,
    hls::stream<axis8_t>& data_out,
    weight_t weights[9],
    bias_t bias,
    dim_t height,
    dim_t width,
    shift_t out_shift,
    ap_uint<1> relu_en
) {
    // ---- Interface Pragmas ----
    #pragma HLS INTERFACE axis port=data_in       // Streaming input activations
    #pragma HLS INTERFACE axis port=data_out      // Streaming output activations
    #pragma HLS INTERFACE s_axilite port=weights   bundle=ctrl  // 3x3 kernel weights
    #pragma HLS INTERFACE s_axilite port=bias      bundle=ctrl  // Pre-scaled bias
    #pragma HLS INTERFACE s_axilite port=height    bundle=ctrl  // Feature map height
    #pragma HLS INTERFACE s_axilite port=width     bundle=ctrl  // Feature map width
    #pragma HLS INTERFACE s_axilite port=out_shift bundle=ctrl  // Requantization shift
    #pragma HLS INTERFACE s_axilite port=relu_en   bundle=ctrl  // ReLU enable flag
    #pragma HLS INTERFACE s_axilite port=return    bundle=ctrl  // Block-level control (ap_ctrl_hs)

    // ---- Copy weights to local registers for constant-time access ----
    weight_t w_local[9];
    #pragma HLS ARRAY_PARTITION variable=w_local complete
    LOAD_WEIGHTS:
    for (int i = 0; i < 9; i++) {
        #pragma HLS UNROLL
        w_local[i] = weights[i];
    }

    // ---- Line buffer: stores 2 completed rows for the 3x3 window ----
    // line_buf[0][c] holds pixel data from row (current_row - 2) at column c
    // line_buf[1][c] holds pixel data from row (current_row - 1) at column c
    // Not static: each invocation processes one complete channel.
    act_t line_buf[2][MAX_WIDTH];
    #pragma HLS ARRAY_PARTITION variable=line_buf complete dim=1

    // Initialize line buffer to zero for clean border padding
    INIT_LB:
    for (int c = 0; c < MAX_WIDTH; c++) {
        #pragma HLS PIPELINE II=1
        line_buf[0][c] = 0;
        line_buf[1][c] = 0;
    }

    // ---- Sliding window: 3 rows x 3 columns of column-delay shift registers ----
    // win[r][0..2] tracks columns (col-2, col-1, col) for window row r.
    // After shifting at iteration (row, col):
    //   win[0] = row (R-2) data at cols [C-2, C-1, C]  (from line_buf[0])
    //   win[1] = row (R-1) data at cols [C-2, C-1, C]  (from line_buf[1])
    //   win[2] = row R     data at cols [C-2, C-1, C]  (from stream)
    // The window center at win[1][1] corresponds to pixel (row-1, col-1).
    act_t win[3][3];
    #pragma HLS ARRAY_PARTITION variable=win complete dim=0

    // ---- Main pixel processing loop ----
    // Loop runs (H+1) x (W+1) iterations:
    //   - Input is read when row < H and col < W  (H*W reads)
    //   - Output is written for center (row-1, col-1) when in [0,H) x [0,W)
    //     (H*W writes)
    //   - Extra row and column feed zeros to produce bottom and right border
    //     outputs.
    PIXEL_ROW:
    for (int row = 0; row < (int)height + 1; row++) {
        // Reset column shift registers at start of each row
        win[0][0] = 0; win[0][1] = 0; win[0][2] = 0;
        win[1][0] = 0; win[1][1] = 0; win[1][2] = 0;
        win[2][0] = 0; win[2][1] = 0; win[2][2] = 0;

        PIXEL_COL:
        for (int col = 0; col < (int)width + 1; col++) {
            #pragma HLS PIPELINE II=1
            #pragma HLS DEPENDENCE variable=line_buf inter false

            // --- Step 1: Read input pixel (only within input bounds) ---
            act_t cur_pixel = 0;
            if (row < (int)height && col < (int)width) {
                axis8_t pkt_in = data_in.read();
                cur_pixel = (act_t)pkt_in.data;
            }

            // --- Step 2: Read line buffer at current column (before update) ---
            // lb0_val = pixel from 2 rows ago at this column
            // lb1_val = pixel from 1 row ago at this column
            act_t lb0_val = 0;
            act_t lb1_val = 0;
            if (col < (int)width) {
                lb0_val = line_buf[0][col];
                lb1_val = line_buf[1][col];
            }

            // --- Step 3: Update line buffer (shift rows down) ---
            if (col < (int)width) {
                line_buf[0][col] = lb1_val;    // Previous row-1 becomes row-2
                line_buf[1][col] = cur_pixel;  // Current pixel becomes row-1
            }

            // --- Step 4: Shift window columns left, insert new rightmost ---
            win[0][0] = win[0][1]; win[0][1] = win[0][2]; win[0][2] = lb0_val;
            win[1][0] = win[1][1]; win[1][1] = win[1][2]; win[1][2] = lb1_val;
            win[2][0] = win[2][1]; win[2][1] = win[2][2]; win[2][2] = cur_pixel;

            // --- Step 5: Determine output position ---
            // Window center (win[1][1]) corresponds to pixel (row-1, col-1)
            int out_row = row - 1;
            int out_col = col - 1;

            // --- Step 6: Produce output if center is within image bounds ---
            if (out_row >= 0 && out_row < (int)height &&
                out_col >= 0 && out_col < (int)width) {

                // 6a: Apply zero-padding mask
                // win[ky][kx] maps to image position (out_row+ky-1, out_col+kx-1)
                // Elements outside [0,H) x [0,W) are zeroed.
                act_t padded_win[3][3];
                #pragma HLS ARRAY_PARTITION variable=padded_win complete dim=0

                MASK_ROW:
                for (int ky = 0; ky < 3; ky++) {
                    #pragma HLS UNROLL
                    MASK_COL:
                    for (int kx = 0; kx < 3; kx++) {
                        #pragma HLS UNROLL
                        int img_r = out_row + ky - 1;
                        int img_c = out_col + kx - 1;
                        bool valid = (img_r >= 0) && (img_r < (int)height) &&
                                     (img_c >= 0) && (img_c < (int)width);
                        padded_win[ky][kx] = valid ? win[ky][kx] : (act_t)0;
                    }
                }

                // 6b: 3x3 MAC (all 9 multiplies fully unrolled)
                acc_t acc = bias;
                KERNEL_ROW:
                for (int ky = 0; ky < 3; ky++) {
                    #pragma HLS UNROLL
                    KERNEL_COL:
                    for (int kx = 0; kx < 3; kx++) {
                        #pragma HLS UNROLL
                        acc += (acc_t)padded_win[ky][kx] *
                               (acc_t)w_local[ky * 3 + kx];
                    }
                }

                // 6c: Optional ReLU (clamp negative accumulator to zero)
                if (relu_en && acc < 0) {
                    acc = 0;
                }

                // 6d: Requantize (arithmetic right-shift) and clamp to INT8
                acc_t shifted = acc >> out_shift;
                act_t out_val;
                if (shifted > 127) {
                    out_val = 127;
                } else if (shifted < -128) {
                    out_val = -128;
                } else {
                    out_val = (act_t)shifted;
                }

                // 6e: Write output pixel to stream
                axis8_t pkt_out;
                pkt_out.data = out_val;
                pkt_out.keep = 1;
                pkt_out.strb = 1;
                // Assert TLAST on the final output pixel
                pkt_out.last = (out_row == (int)height - 1 &&
                                out_col == (int)width - 1) ? 1 : 0;
                data_out.write(pkt_out);
            }
        }
    }
}
