/*
 * depthwise_conv -- HLS IP Header
 *
 * Description: 3x3 depthwise convolution with INT8 data path,
 *              line buffer architecture, zero-padding, optional ReLU,
 *              and shift-based requantization.
 * Author:      Generated by Vitis HLS Automation Environment
 */

#ifndef DEPTHWISE_CONV_HPP
#define DEPTHWISE_CONV_HPP

// ============================================================
// Vitis HLS Includes
// ============================================================
#include <ap_int.h>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

// ============================================================
// Constants
// ============================================================
const int MAX_WIDTH   = 128;   // Maximum supported feature map width
const int KERNEL_SIZE = 3;     // Fixed 3x3 kernel

// ============================================================
// Type Definitions
// ============================================================

// AXI-Stream element type (top-level ports only)
typedef ap_axiu<8, 0, 0, 0> axis8_t;

// Core data types
typedef ap_int<8>   act_t;     // Activations: signed INT8 [-128, 127]
typedef ap_int<8>   weight_t;  // Weights: signed INT8 [-128, 127]
typedef ap_int<32>  bias_t;    // Bias: INT32, pre-scaled to accumulator domain
typedef ap_int<32>  acc_t;     // Accumulator: 32-bit signed
typedef ap_uint<5>  shift_t;   // Requantization right-shift (0-31)
typedef ap_uint<8>  dim_t;     // Feature map dimensions (3-128)

// ============================================================
// Top Function Prototype
// ============================================================
void depthwise_conv(
    hls::stream<axis8_t>& data_in,
    hls::stream<axis8_t>& data_out,
    weight_t weights[9],
    bias_t bias,
    dim_t height,
    dim_t width,
    shift_t out_shift,
    ap_uint<1> relu_en
);

#endif // DEPTHWISE_CONV_HPP
